# Generated by Django 6.0.3 on 2026-03-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_scraped', models.IntegerField(default=0)),
                ('total_processed', models.IntegerField(default=0)),
                ('total_errors', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', '실행 중'), ('done', '완료'), ('failed', '실패')], default='running', max_length=20)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(blank=True)),
                ('pharmacy_name', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('big_category', models.CharField(blank=True, max_length=50)),
                ('is_salary_disclosed', models.BooleanField(blank=True, null=True)),
                ('is_one_time_work', models.BooleanField(blank=True, null=True)),
                ('one_time_hourly_wage', models.FloatField(blank=True, null=True)),
                ('wage_type', models.CharField(blank=True, max_length=50)),
                ('wage_raw', models.FloatField(blank=True, null=True)),
                ('hourly_wage', models.FloatField(blank=True, null=True)),
                ('net_salary', models.FloatField(blank=True, null=True)),
                ('weekday_work_days', models.FloatField(blank=True, null=True)),
                ('weekday_start_time', models.FloatField(blank=True, null=True)),
                ('weekday_end_time', models.FloatField(blank=True, null=True)),
                ('weekend_work_days', models.FloatField(blank=True, null=True)),
                ('weekend_start_time', models.FloatField(blank=True, null=True)),
                ('weekend_end_time', models.FloatField(blank=True, null=True)),
                ('hours_per_week', models.FloatField(blank=True, null=True)),
                ('hours_per_month', models.FloatField(blank=True, null=True)),
                ('monthly_leave', models.CharField(blank=True, max_length=10)),
                ('experience_required', models.TextField(blank=True)),
                ('meal_info', models.TextField(blank=True)),
                ('llm_model', models.CharField(blank=True, max_length=100)),
                ('gpt_summary', models.TextField(blank=True)),
                ('gpt_output_log', models.TextField(blank=True)),
                ('gpt_error_log', models.TextField(blank=True)),
                ('has_error', models.BooleanField(default=False)),
                ('error_corrected', models.BooleanField(default=False)),
                ('user_reviewed', models.BooleanField(default=False)),
                ('user_comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['big_category'], name='postings_jo_big_cat_bd58ce_idx'), models.Index(fields=['platform'], name='postings_jo_platfor_ab3236_idx'), models.Index(fields=['has_error'], name='postings_jo_has_err_facb4d_idx'), models.Index(fields=['user_reviewed'], name='postings_jo_user_re_d5b197_idx')],
            },
        ),
    ]
