# Generated by Django 6.0.3 on 2026-03-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='log_output',
            field=models.TextField(blank=True),
        ),
    ]
