# Generated by Django 6.0.3 on 2026-03-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_pipelinerun_log_output'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='hourly_wage',
            new_name='net_hourly_wage',
        ),
    ]
