# Generated by Django 6.0.3 on 2026-03-24 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_rename_hourly_wage_to_net_hourly_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='공고 날짜'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='user_reviewed',
            field=models.BooleanField(default=False, verbose_name='관리자 리뷰'),
        ),
        migrations.CreateModel(
            name='AdminCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('posting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_check', to='postings.jobposting')),
            ],
        ),
    ]
