# Generated by Django 6.0.3 on 2026-03-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_add_admincheck_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='error_corrected',
        ),
    ]
