# Generated by Django 6.0.3 on 2026-05-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0005_remove_error_corrected'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincheck',
            name='source',
            field=models.CharField(choices=[('admin', '관리자 검토'), ('llm', 'LLM 자동 검토')], default='admin', max_length=20, verbose_name='검토 주체'),
        ),
    ]
