# Generated by Django 6.0.3 on 2026-05-31 01:34

from django.db import migrations, models
from django.db.models import F


def backfill_updated_at(apps, schema_editor):
    """기존 공고의 updated_at 을 inserted_at 으로 백필 (update 는 auto_now 를 우회)."""
    JobPosting = apps.get_model('postings', 'JobPosting')
    JobPosting.objects.update(updated_at=F('inserted_at'))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0006_admincheck_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name='수정 시각'),
        ),
        migrations.RunPython(backfill_updated_at, noop),
    ]
