# Generated by Django 6.0.3 on 2026-06-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0007_jobposting_updated_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobposting',
            name='postings_jo_user_re_d5b197_idx',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='user_reviewed',
        ),
    ]
