# Generated by Django 6.0.3 on 2026-06-03 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0008_remove_jobposting_postings_jo_user_re_d5b197_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincheck',
            name='source',
            field=models.CharField(choices=[('admin', '관리자 검토'), ('llm', 'LLM 자동 검토'), ('agent', '대화형 agent 검토')], default='admin', max_length=20, verbose_name='검토 주체'),
        ),
        migrations.CreateModel(
            name='AgentReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcript', models.JSONField(default=list)),
                ('applied_changes', models.JSONField(default=list)),
                ('generated_comment', models.TextField(blank=True)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='postings.jobposting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
