# Generated by Django 6.0.3 on 2026-06-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0009_alter_admincheck_source_agentreviewsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='wage_raw',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='wage_type',
        ),
    ]
