# Generated by Django 6.0.3 on 2026-06-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0010_remove_jobposting_wage_raw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
                ('posting_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
