# Generated by Django 6.0.3 on 2026-06-20 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0011_dashboardsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='공고 날짜')),
                ('title', models.TextField(blank=True)),
                ('pharmacy_name', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('big_category', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', '처리 대기'), ('processed', 'JobPosting 생성 완료'), ('skipped_no_salary', '급여 미명시로 건너뜀'), ('error', '처리 중 에러')], db_index=True, default='pending', max_length=20)),
                ('error_log', models.TextField(blank=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_postings', to='postings.pipelinerun', verbose_name='스크래핑 회차')),
            ],
            options={
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['status'], name='postings_ra_status_03cc26_idx')],
            },
        ),
    ]
