# Generated by Django 6.0.3 on 2026-06-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0012_rawposting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinerun',
            name='total_processed',
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='big_categories',
            field=models.JSONField(blank=True, default=list, verbose_name='지역 대분류'),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='수집 개수'),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='start_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='시작 ID'),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='step',
            field=models.IntegerField(blank=True, null=True, verbose_name='스텝'),
        ),
    ]
