# Generated by Django 6.0.3 on 2026-06-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0013_pipelinerun_scrape_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='last_scraped_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='마지막 성공 ID'),
        ),
    ]
