# Generated by Django 6.0.3 on 2026-06-28 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0014_pipelinerun_last_scraped_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='llm_cost_usd',
            field=models.FloatField(default=0.0, verbose_name='LLM 누적 비용(USD)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='llm_total_tokens',
            field=models.IntegerField(default=0, verbose_name='LLM 누적 토큰'),
        ),
        migrations.CreateModel(
            name='LLMUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('stage', models.CharField(choices=[('process', 'pre-2 프로세싱'), ('verify', 'LLM 자동 검토'), ('agent', '대화형 agent 검토')], max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('raw_posting_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('api_calls', models.IntegerField(default=0)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('job_posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='postings.jobposting')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stage'], name='postings_ll_stage_462493_idx'), models.Index(fields=['created_at'], name='postings_ll_created_4dabc1_idx')],
            },
        ),
    ]
