# -*- coding: utf-8 -*-
"""약사 구인공고_Error처리_with_GPT-4o.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cxkleevot-3lzWjefd_t6_NvBhuUFnNX

'output_error.csv' 파일 필요
"""

# Commented out IPython magic to ensure Python compatibility.
# # @title 🇰🇷 Colab 환경에서 matplotlib에 한글 폰트 추가하기
# # 참고 : https://blog.naver.com/ansrl23/222884519294
# %%capture
# !sudo apt-get install -y fonts-nanum
# !sudo fc-cache -fv
# !rm ~/.cache/matplotlib -rf
# 
# # !!! 이 cell을 실행하고 나서 runtime 재시작을 해 줘야함 !!!

"""# 1️⃣ Requirements"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install openai

# @title Tokens, IDs, Keys
# ======================= Notion API =======================
import os
from dotenv import load_dotenv

load_dotenv()  # .env 파일에서 환경변수 불러오기

NOTION_TOKEN = os.getenv('NOTION_TOKEN')
DATABASE_ID = os.getenv('DATABASE_ID')

# ======================= OpenAI API =======================
# https://platform.openai.com/account/api-keys 에서 발급 받음
# https://platform.openai.com/usage 에서 사용량 볼 수 있음
# https://openai.com/api/pricing/ 에서 모델별 가격 볼수 있음
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# @title Requirements
import pandas as pd
import torch
import matplotlib.pyplot as plt
import json
import re
import requests
from datetime import datetime, timezone
import pprint

# matplotlib 폰트 설정하기
plt.rc('font', family='NanumBarunGothic')

# Pandas 출력 옵션 설정
#  : to_string() 함수 사용시 content가 너무 길면 뒷부분이 ...으로 짤리는 경우가 있어서 이를 방지하기 위함
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

specific_date_new_data = 'New Data 2024_12' # @param {type:'string'}

# @title Notion DB upload 함수들
def create_page(database_id, notion_token, data: dict):
    '''
    노션 데이터 베이스에 새로운 페이지를 추가하는 함수

    < 사용 예시 >
    cur_url = "https://www.naver.com/"
    date = "2023-03-15"
    title = "테스트 한 줄"
    address = "테스트 주소"
    body = "테스트 본문"

    data = {
        '링크': {'url': cur_url},
        '등록일': {'date': {'start': date, 'end': None}},
        '약국 이름 - 공고 제목': {'title': [{'text': {'content': title}}]},
        '약국 주소': {'rich_text': [{'text': {'content': address}}]},
        '본문': {'rich_text': [{'text': {'content': body}}]}
    }

    create_page(data) # 출력값 200은 잘 추가됨, 400은 추가 실패함을 의미.
    '''
    create_url = "https://api.notion.com/v1/pages"
    headers = {
        "Authorization": f"Bearer {notion_token}",
        "Content-Type": "application/json",
        "Notion-Version": "2022-06-28"
    }
    payload = {
        "parent": {"database_id": database_id},
        "properties": data
    }

    res = requests.post(create_url, headers=headers, json=payload)
    print(res.status_code)
    return res

def transform_for_upload(data_dict):
    '''
    데이터 딕셔너리를 노션 API에 맞게 변환하는 함수
    '''
    transformed_data = {}
    for key, value in data_dict.items():
        if value is not None:
            if key in ['링크']:
                transformed_data[key] = {'url': value}
            elif key in ['등록일']:
                transformed_data[key] = {'date': {'start': value, 'end': None}}
            elif key in ['공고 제목']:
                transformed_data[key] = {'title': [{'text': {'content': value}}]}
            elif key in ['근무 요일', '약국 명칭', '본문', 'LLM model', 'GPT 요약문', 'GPT 2nd Run', 'GPT Error', '경력 요구', '월차', '식사 관련', '플랫폼', 'Error났던 LLM 출력']:
                transformed_data[key] = {'rich_text': [{'text': {'content': value}}]}
            elif key in ['지역', '지역 대분류']:
                transformed_data[key] = {'select': {'name': value}}
            elif key in ['공고에 급여 명시 여부', '일회성 근무 여부', 'New Data', specific_date_new_data, 'Error 교정 작업']:
                transformed_data[key] = {'checkbox': value}
            elif key in ['일회성 근무 시급', '세후 월급', '평일 근무 일수', '평일 출근 시각', '평일 퇴근 시각', '주말 근무 일수', '주말 출근 시각', '주말 퇴근 시각']:
                transformed_data[key] = {'number': value}
            else:
                pass # data_dict 중에서 notion에 없는 column의 경우에는 그냥 스킵함. (e.g. 그냥 중간에 검산용으로 쓰이는 변수들)
    return transformed_data

def upload_notion_db(database_id, notion_token, data_dict):
    '''
    노션 데이터베이스에 데이터를 업로드하는 함수
    '''
    data_not_none = transform_for_upload(data_dict)
    # pprint.pprint(data_not_none)
    create_page(database_id, notion_token, data_not_none) # 출력값 200은 잘 추가됨, 400은 추가 실패함을 의미.

"""```python
# dict_for_upload = {
#     **task_setting_dict,
#     **posting_info_dict,
#     **llm_output_dict,
#     **process_dict
# }

task_setting_dict = {
    'New Data' : True,  # 노션상에서 새로 추가된 data인지 구분하기 위해 편의상 marker를 다는 것
    'Error 교정 작업' : True, # 노션상에서 에러 교정한 data인지 구분하기 위해 편의상 marker를 다는 것
    'Error났던 LLM 출력' : previous_llm_output, # 이전 LLM의 출력 참고용으로 기록해줌
    'LLM model' : MODEL_NAME, # 이번 Task에서 사용한 LLM model 이름
}

posting_info_dict ={  # 공고에 나온 정보들 -> 그대로 dict_for_upload에 넣으면 됨
    '공고 제목' : title,
    '등록일' : date,
    '링크' : cur_url,
    '본문' : body,
    '약국 명칭' : name,
    '지역' : city,
    '지역 대분류' : big_category,
    '플랫폼' : platform
}

llm_output_dict = {  # LLM이 만든 출력들 -> 그대로 dict_for_upload에 넣으면 됨 (어차피 transform_for_upload()에서 노션 column이 없는 항목들이 지워지므로)
    "공고에 급여 명시 여부": (boolean),
    "일회성 근무 여부": (boolean),
    "일회성 근무 시급": (number | null),
    "근무 요일": (string | null),
    "평일 근무 일수": (number | null),
    "평일 출근 시각": (number | null),
    "평일 퇴근 시각": (number | null),
    "평일 총 근무 시간": (number | null),
    "주말 근무 일수": (number | null),
    "주말 출근 시각": (number | null),
    "주말 퇴근 시각": (number | null),
    "월차": (string | null),
    "경력 요구": (string | null),
    "식사 관련": (string | null),
    # "세후 금액 여부": (boolean),
    # "급여 유형" : (string | null),
    # "급여": (number | null),
    # "일회성 근무 일수": (number | null),
    # "일회성 근무 출근 시각": (number | null),
    # "일회성 근무 퇴근 시각": (number | null),
    # "일회성 근무 총 근무 시간": (number | null),
    # "주말 총 근무 시간": (number | null),
    # "주당 총 근무 시간": (number | null),
    # "월 총 근무 시간": (number | null),
    # "시급": (number | null),
}

to_process_dict = { # 얘네를 요리해서 Error detection해서 걸러내고 아래 processed_dict로 변환시켜야 함.
    "세후 금액 여부": (boolean),
    "급여 유형" : (string | null),
    "급여": (number | null),
    "일회성 근무 일수": (number | null),
    "일회성 근무 출근 시각": (number | null),
    "일회성 근무 퇴근 시각": (number | null),
    "일회성 근무 총 근무 시간": (number | null),
    "주말 총 근무 시간": (number | null),
    "주당 총 근무 시간": (number | null),
    "월 총 근무 시간": (number | null),
    "시급": (number | null),
}

process_dict = { # LLM output을 바탕으로 이런저런 processing을 거친 결과  ->  dict_for_upload에 넣으면 됨
    'GPT 요약문' : refined_body,
    'GPT 2nd Run' : final_answer,
    'GPT Error' : error_history,
    '세후 월급' : net_salary,
}

previous_notion_formula_dict = { # 이전 LLM 출력을 바탕으로 노션에서 formula로 계산한 결과물 -> 업로드 안하고 그냥 참고용으로만 쓰면 될듯
    '시급(엄밀히)',
    '주당 근무 일수',
    '시간/month',
}
```

# 💊🆘 Error난 공고들 csv 파일 불러오기
"""

# @title read_csv( )
df = pd.read_csv('output_error.csv')

# '등록일'이 '%Y년 %m월 %d일' format이라 '%Y-%m-%d' format으로 바꿔줌.
df['등록일_datetime'] = pd.to_datetime(df['등록일'], format='%Y년 %m월 %d일')
df['등록일'] = df['등록일_datetime'].dt.strftime('%Y-%m-%d') # 문자열로 다시 변환

print('df length : ', len(df))

df.head(1)

# @title Toy Example
start = None  # @param {type:'integer'}
df = df[start:]

df[['지역', '공고 제목', '약국 명칭']].head(10)

"""## 참고) 살펴보기"""

df.info()

df.columns

# @title df의 값들 histogram 그려보기
# '지역 대분류' 값들의 빈도수 계산
select_col = '일회성 근무 여부' # @param['New Data', '공고에 급여 명시 여부', '내가 검토시 체크', '지역 대분류', '지역', '일회성 근무 여부', '일회성 근무 시급', '플랫폼', '등록일_datetime', 'LLM model', '평일 근무 일수', '평일 출근 시각', '평일 퇴근 시각', '주말 근무 일수', '주말 출근 시각', '주말 퇴근 시각', '월차', '경력 요구', '주당 근무 일수', '시간/month']
category_counts = df[select_col].value_counts()

# xticks 수에 따른 가로 크기 조정
num_ticks = len(category_counts.index)
fig_width = max(4, num_ticks * 0.2)  # 기본값 8, xticks 당 0.5

# 히스토그램 그리기
plt.figure(figsize=(fig_width, 6))  # 가로 크기를 동적으로 설정
plt.bar(category_counts.index, category_counts.values, width=0.3)
plt.xlabel(select_col)
plt.ylabel('빈도수')
plt.title('{} 히스토그램'.format(select_col))
plt.xticks(rotation=45, ha='right')  # x축 레이블 회전

# 막대 꼭대기에 빈도수 표시
for idx, value in zip(category_counts.index, category_counts.values):
    plt.text(idx, value, str(value), ha='center', va='bottom', color='black')

# 빈도수의 총합 출력
total_count = category_counts.sum()
print('총 공고수:', len(df))
print('빈도수 합:', total_count)
print('None 값 개수:', df[select_col].isnull().sum())

plt.tight_layout()  # 레이블이 겹치지 않도록 조정
plt.show()

"""# 2️⃣ LLM Model"""

# @title run_llm( )
#============================== OpenAI API ===================================#
import openai
# 유료 결제 해야함...
# https://platform.openai.com/usage 에서 사용량 볼 수 있음
# https://openai.com/api/pricing/ 에서 모델별 api 사용료 볼 수 있음

# openai API 키 인증
openai.api_key = OPENAI_API_KEY
#=============================================================================#

MODEL_NAME = "gpt-4o" # @param ["gpt-4-turbo", "gpt-4o-mini", "gpt-4o", "o1-mini", "o1-preview"]

def run_llm(query, model_name=MODEL_NAME, run_name='Run', few_shot=None):
    if few_shot is not None:
        query = query + '\n예시(few-shot) :\n' + few_shot + '\n'  # few_shot을 제공할 경우, query에 덧붙여 줌.
    else:
        pass

    messages = [
            {"role": "system", "content": "당신은 도움을 주는 assistant입니다."},
            {"role": "user", "content": query}
    ]

    try:
        # ChatGPT API 호출하기
        response = openai.chat.completions.create(
            model=MODEL_NAME,
            messages=messages
        )
        refined_body = response.choices[0].message.content
        print('='*25, 'LLM ({}) {} '.format(model_name, run_name), '='*25)
        print(refined_body)
        print('='*50, '\n\n')
        return refined_body
    except Exception as e:
        print('\n' + '🆘'*50 + '\n', n, '번 글 at {}\n'.format(run_name), e, '\n' + '🆘'*50 + '\n')
        return None

# @title extract_json_from_response( ) : LLM의 응답을 JSON 형식으로 파싱하여 dict를 반환하는 함수
def extract_json_from_response(response):
    '''
    LLM의 응답을 JSON 형식으로 파싱하여 dict를 반환하는 함수
    '''
    # regex를 사용하여 dictionary 부분만 추출
    pattern = re.compile(r'\{.*\}', re.DOTALL)
    match = pattern.search(response)

    if match:
        json_string = match.group()

        try:
            # 정규 표현식을 사용하여 모든 주석 제거 (// 스타일 주석과 /* */ 스타일 주석)
            json_string = re.sub(r'//.*?(?=\n)|/\*.*?\*/', '', json_string, flags=re.S)

            # 문자열을 Python dictionary로 변환
            result_dict = json.loads(json_string)
            # 결과 반환
            return result_dict, json_string
        except json.JSONDecodeError as e:
            print("JSON is invalid")
            print('JSON string :\n', json_string)
            print(f"Error: {e}")
            return None, json_string
    else:
        print("LLM output에서 dictionary pattern을 추출할 수 없습니다.")
        return None, None

# LLM 응답 예시
# response = '{"평일 출근 시각": 8} 근무시간이 9시부터 17시까지 이므로 8시간이 됩니다.'
# response_dict = extract_json_from_response(response)
# print(response_dict)

# is_salary_info = response_dict['공고에 급여 명시 여부']
# one_time_work = response_dict['단기근무']
# one_time_work_hourly_wage = response_dict['단기근무 시급']
# error_history = response_dict['GPT Error']
# gpt_output_history = response_dict['GPT 2nd Run']
# net_salary = response_dict['세후 급여']
# weekday_work_days = response_dict['평일 근무 일수']
# weekday_start_time = response_dict['평일 출근 시각']
# weekday_end_time = response_dict['평일 퇴근 시각']
# weekend_work_days = response_dict['주말 근무 일수']
# weekend_start_time = response_dict['주말 출근 시각']
# weekend_end_time = response_dict['주말 퇴근 시각']
# monthly_leave = response_dict['월차']
# experience_requirement = response_dict['경력 요구']
# meal = response_dict['식사 관련']
# notion_hourly_wage = response_dict['시급(엄밀히)']
# notion_work_days_per_week = response_dict['주당 근무 일수']
# notion_work_hours_per_month = response_dict['시간/month']

# @title error_check( )
def error_message(message, error_history):
    print(message)
    error_history = error_history + message + '\n'
    print('='*100, '\n')
    return error_history

def compare_values(value_1, value_2, threshold=0.1):
    '''
    두 값이 비슷한지 판단하는 함수
    LLM 이 사칙연산 계산에 정확도가 낮기 때문에 이를 체크하기 위함.
    두 값이 threshold 만큼의 % 이상 차이가 나면 False를 반환.
    '''
    # value_1과 value_2가 사칙연산 가능한 숫자인지 확인
    if not isinstance(value_1, (int, float)) or not isinstance(value_2, (int, float)):
        print('비교하려는 두 값중 적어도 하나가 숫자가 아니라 비교할 수 없습니다.')
        return False
    else:
        if abs(value_1 - value_2)/(value_1 + 0.0001) < threshold:  # divide by zero 방지
            return True
        else:
            return False

def error_check(d, error_history='', Min_hourly_wage=1.8, Max_hourly_wage=5.5, Max_work_per_week=56):
    '''
    llm_output_dict를 넣으면 error를 체크해서 error 메시지들을 error_history에 기록해서 반환하는 함수
    심각한 error의 경우 -> return error_history를 통해 에러 체크 종료
    심각하지 않은 error의 경우 -> 그냥 에러 메시지만 기록하고 넘어감
    이 함수는 llm_output_dict 자체를 수정하진 않는다.
    '''
    DIFF_THRESHOLD = 0.1  # 위에 compare_values 함수에 threshold 인수에 넣을 파라미터.

    # 각 변수들이 할당되지 않았을 경우 None을 반환하도록 초기 설정해줌
    total_work_hours_per_week = None
    hourly_wage = None

    # '공고에 급여 명시 여부' = False 인 공고들은 이미 앞에서 다 걸러졌음.
    # '급여'가 None이거나 숫자가 아닌 경우
    if not isinstance(d['급여'], (float, int)):
        if not isinstance(d['시급'], (float, int)):
            if not isinstance(d['일회성 근무 시급'], (float, int)):
                gpt_error = '''
                [ ERROR 발생 ] "급여", "시급", "일회성 근무 시급" 값이 모두 없습니다.
                공고에 급여 명시 여부 = True 가 맞는지 재확인이 필요합니다. [ 확인 요망 ]
                '''
                error_history = error_message(gpt_error, error_history)
                return error_history, total_work_hours_per_week, hourly_wage  # 급여 관련된 정보가 전혀 없으므로 에러 체크 종료

    ###########################  for 일회성 근무  #################################
    if d['일회성 근무 여부']:
        # ============= 일회성 근무 시급이 None이거나 숫자가 아닌 경우 ===================
        if not isinstance(d['일회성 근무 시급'], (float, int)):
            if not isinstance(d['급여'], (float, int)):
                gpt_error = '''
                [ ERROR 발생 ] 일회성 근무 시급 값이 없습니다.
                일회성 근무가 맞는지, 공고에 급여 명시 여부 = True 가 맞는지 재확인이 필요합니다. [ 확인 요망 ]
                '''
                error_history = error_message(gpt_error, error_history)
            else:
                gpt_error = '''
                [ ERROR 발생 ] "일회성 근무 시급" 값은 없고, 대신 "급여" 값이 명시되어 있습니다.
                구인 공고가 일회성 근무가 맞다면 "급여"는 None으로 설정하고 "일회성 근무 시급"값을 작성해야 합니다. [ 확인 요망 ]
                '''
                error_history = error_message(gpt_error, error_history)

        else:  # d['일회성 근무 시급']이 숫자인 경우, 범위 안에 들어오는지 판단.
            # =============== 일회성 근무 시급이 정상 범위 내인지 확인 ==================
            if Min_hourly_wage <= d['일회성 근무 시급'] <= Max_hourly_wage:
                pass
            else: # 문제 상황
                gpt_error = '''
                [ ERROR 발생 ] 일회성 근무 시급이 {}만원으로 정상 범위({} ~ {})를 벗어났습니다. 시간당 책정된 급여가 맞는지 재확인이 필요합니다.
                일급이나 주급, 월급, 연봉의 경우 근무시간으로 나누어 시간당 급여로 환산해야합니다.[ 확인 요망 ]
                '''.format(d['일회성 근무 시급'], Min_hourly_wage, Max_hourly_wage)
                error_history = error_message(gpt_error, error_history)

    ###########################  for 지속성 근무  #################################
    else:
        # ============================ 급여 유형 =================================
        wage_type_list = ['yearly', 'annual', 'monthly', 'weekly', 'daily', 'hourly',
                          'yearly wage', 'yearly salary', 'annual wage', 'annual salary',
                          'monthly wage', 'weekly wage', 'daily wage', 'hourly wage',
                          '연봉', '월급', '주급', '일급', '일당', '시급']
        if d['급여 유형'] is not None:
            wage_type = d['급여 유형'].lower()
            if wage_type not in wage_type_list: # 문제 상황
                gpt_error = '''
                [ ERROR 발생 ] 급여 종류가 연봉/월급/주급/일급/시급 중에 하나로 표시되어야 하는데 그렇지 않았습니다.
                공고에 표시된 급여가 연봉/월급/주급/일급/시급인지 명시되지 않은 경우 그냥 '월급'으로 간주하여 작성합니다. [ 확인 요망 ]
                '''
                error_history = error_message(gpt_error, error_history)
                # 조치사항
                d['급여 유형'] = 'monthly'
                wage_type = 'monthly'
        else:
            wage_type = None

        # ================== 값들이 None이거나 숫자가 아닌 경우 =======================
        if not isinstance(d['평일 근무 일수'], (float, int)):
            d['평일 근무 일수'] = 0
        if not isinstance(d['평일 출근 시각'], (float, int)):
            d['평일 출근 시각'] = None
        if not isinstance(d['평일 퇴근 시각'], (float, int)):
            d['평일 퇴근 시각'] = None

        if not isinstance(d['주말 근무 일수'], (float, int)):
            d['주말 근무 일수'] = 0
        if not isinstance(d['주말 출근 시각'], (float, int)):
            d['주말 출근 시각'] = None
        if not isinstance(d['주말 퇴근 시각'], (float, int)):
            d['주말 퇴근 시각'] = None

        if (d['평일 근무 일수'] + d['주말 근무 일수']) == 0: # 문제 상황
            gpt_error = '''
            [ ERROR 발생 ] 평일 근무 일수와 주말 근무 일수가 모두 0일입니다.
            공고에 근무 요일이 명확하게 나와있지 않다면, 공고에 나와있는 조건들을 준수하는 범위 내에서 적당한 요일을 가정하여 작성하도록 합니다. [ 확인 요망 ]
            '''
            error_history = error_message(gpt_error, error_history)
            # 조치사항
            work_hours_per_day = 0
            return error_history, total_work_hours_per_week, hourly_wage  # 에러체크 종료
        else:
            pass

        if (d['평일 근무 일수']>5) or (d['주말 근무 일수']>2): # 문제 상황
            gpt_error = '''
            [ ERROR 발생 ] 평일 근무 일수가 5일을 초과하거나 주말 근무 일수가 2일을 초과합니다.
            월, 화, 수, 목, 금 중에 일하는 날 수를 세어 "평일 근무 일수"을 작성해야 합니다. 따라서 5를 초과할 수 없습니다.
            토, 일 중에 일하는 날 수를 세어 "주말 근무 일수"을 작성해야 합니다. 고로 2를 초과할 수 없습니다.  [ 확인 요망 ]
            '''
            error_history = error_message(gpt_error, error_history)
        else:
            pass

        # ===================== 평일 총 근무시간 검산 ===============================
        if all([d['평일 근무 일수'], d['평일 출근 시각'], d['평일 퇴근 시각']]):
            total_weekday_work_hours = (d['평일 퇴근 시각'] - d['평일 출근 시각']) * d['평일 근무 일수']
            print('평일 총 근무 시간 : {} 시간'.format(total_weekday_work_hours))
            if d['평일 총 근무 시간'] is None:
                gpt_error = '''
                [ ERROR 발생 ] "평일 총 근무 시간" 값이 누락되어 있습니다.
                평일 근무 일수 및 출퇴근 시각을 활용하여 계산하면 {} 시간이 나옵니다.
                이 값이 맞는지 검산이 필요합니다. [ 확인 요망 ]
                '''.format(total_weekday_work_hours)
                error_history = error_message(gpt_error, error_history)

        else:
            print('평일 근무 시간 계산에 필요한 정보("평일 근무 일수", "평일 출근 시각", "평일 퇴근 시각") 중 적어도 하나가 누락되어 계산이 불가합니다.')
            total_weekday_work_hours = 0

        # ===================== 주말 총 근무시간 검산 ===============================
        if all([d['주말 근무 일수'], d['주말 출근 시각'], d['주말 퇴근 시각']]):
            total_weekend_work_hours = (d['주말 퇴근 시각'] - d['주말 출근 시각']) * d['주말 근무 일수']
            print('주말 총 근무 시간 : {} 시간'.format(total_weekend_work_hours))
            if d['주말 총 근무 시간'] is None:
                gpt_error = '''
                [ ERROR 발생 ] "주말 총 근무 시간" 값이 누락되어 있습니다.
                주말 근무 일수 및 출퇴근 시각을 활용하여 계산하면 {} 시간이 나옵니다.
                이 값이 맞는지 검산이 필요합니다. [ 확인 요망 ]
                '''.format(total_weekend_work_hours)
                error_history = error_message(gpt_error, error_history)

        else:
            print('주말 근무 시간 계산에 필요한 정보("주말 근무 일수", "주말 출근 시각", "주말 퇴근 시각")중 적어도 하나가 누락되어 계산이 불가합니다.')
            total_weekend_work_hours = 0


        # ===================== 총 근무 시간 [평일 + 주말]  =========================
        total_work_hours_per_week = total_weekday_work_hours + total_weekend_work_hours  # 주당 근무 시간 = 평일 총근무시간 + 주말 총근무시간
        total_work_hours_per_month = total_work_hours_per_week * 4.34 # 월당 근무 시간 = 주당 근무 시간 * 4.34주

        if total_work_hours_per_month == 0: # 문제 상황
            if d['주당 총 근무 시간']:
                total_work_hours_per_week = d['주당 총 근무 시간']
                total_work_hours_per_month = d['주당 총 근무 시간'] * 4.34
            elif d['월 총 근무 시간']:
                total_work_hours_per_month = d['월 총 근무 시간']
                total_work_hours_per_week = d['월 총 근무 시간'] / 4.34
            else:
                gpt_error = '''
                [ ERROR 발생 ] 평일 및 주말 근무 일수와 출퇴근 시각을 통해 계산된 총 근무시간이 0 시간 입니다.
                공고에 근무 요일과 출퇴근 시각이 명시되어 있지 않은지 재확인이 필요합니다.[ 확인 요망 ]
                '''
                error_history = error_message(gpt_error, error_history)
                return error_history, total_work_hours_per_week, hourly_wage  # 에러체크 종료

        else: # total_work_hours_per_month = 0 이 아닌 경우
            # ==================== LLM 이 계산한 주당 총 근무시간 검산 ========================
            if d['주당 총 근무 시간'] is None:
                gpt_error = '''
                [ ERROR 발생 ] "주당 총 근무 시간" 값이 누락되어 있습니다.
                평일 및 주말 근무 일수와 출퇴근 시각을 활용하여 계산하면 {} 시간이 나옵니다.
                이 값이 맞는지 검산이 필요합니다. [ 확인 요망 ]
                '''.format(total_work_hours_per_week)
                error_history = error_message(gpt_error, error_history)
            else:
                # ==================== 주당 근무시간이 음수인지, 너무 큰 값인지 체크 ========================
                if (total_work_hours_per_week > Max_work_per_week): # 문제 상황
                    gpt_error = '''
                    [ ERROR 발생 ] 주당 총 근무시간이 {}시간을 초과했습니다. 이는 매우 이례적인 경우입니다.
                    근무일수와 출퇴근 시각이 맞게 입력되었는지 재확인이 필요합니다. [ 확인 요망 ]
                    '''.format(Max_work_per_week)
                    error_history = error_message(gpt_error, error_history)
                else:
                    pass

                if (total_work_hours_per_week < 0): # 문제 상황
                    gpt_error = '''
                    [ ERROR 발생 ] 주당 총 근무시간이 음수입니다. 근무시간은 음수가 될 수 없습니다.
                    출퇴근 시각이 적절하게 입력되었는지 재확인이 필요합니다.
                    만약 야간 근무라면, 퇴근시각이 익일 새벽 1시인 경우 퇴근시각=25 로 표기해야 합니다.
                    이를 퇴근시각=1 로 표기했다면 근무시간이 음수가 나올 수 있습니다. [ 확인 요망 ]
                    '''
                    error_history = error_message(gpt_error, error_history)
                else:
                    pass

            # ========================= 일평균 근무 시간 ===========================
            # 일당 근무 시간 = 주당 근무 시간 / (평일 근무 일수 + 주말 근무 일수)
            work_hours_per_day = total_work_hours_per_week / (d['평일 근무 일수'] + d['주말 근무 일수'])  # 분모가 0이 되는 경우는 앞에서 return으로 배제함.

        if d['급여'] is not None: # LLM 출력 중 급여값이 있는 경우, 근무시간으로 나눠서 시급을 계산!
            # 근무시간이 0 인 경우는 return 을 통해 제외되었으므로 divide by zero는 걱정 안해도 됨.
            # ========================= 시급 계산 ====================================
            if wage_type in ['monthly', 'monthly wage', '월급']:
                hourly_wage = d['급여'] / total_work_hours_per_month
            elif wage_type in ['weekly', 'weekly wage', '주급']:
                hourly_wage = d['급여'] / total_work_hours_per_week
            elif wage_type in ['daily', 'daily wage', '일급', '일당']:
                hourly_wage = d['급여'] / work_hours_per_day
            elif wage_type in ['hourly', 'hourly wage', '시급']:
                hourly_wage = d['급여']
            elif wage_type in ['yearly wage', 'yearly salary', 'annual wage', 'annual salary', '연봉']:
                hourly_wage = d['급여'] / 12 / total_work_hours_per_month
            else: # 그 외의 경우에는 그냥 월급으로 간주하고 계산.
                hourly_wage = d['급여'] / total_work_hours_per_month

        else:
            if d['시급'] is not None: # LLM 출력 중 "급여" 값은 없는데 "시급" 값은 있는 경우
                hourly_wage = d['시급']  # "시급"을 그대로 사용.
            else:
                gpt_error = '''
                [ ERROR 발생 ] LLM 출력 중 "급여"와 "시급" 값이 누락되어 있습니다.
                공고에 급여 명시 여부 = True 가 맞는지 재확인이 필요합니다. [ 확인 요망 ]
                '''
                error_history = error_message(gpt_error, error_history)
                return error_history, total_work_hours_per_week, hourly_wage  # 에러체크 종료

        # ==================== 시급이 정상 범위를 이탈한 경우 =========================
        if Min_hourly_wage <= hourly_wage <= Max_hourly_wage:
            pass
        else:
            gpt_error = '''
            [ ERROR 발생 ] 시급이 {}만원으로 정상 범위({} ~ {}만원)를 벗어났습니다.
            LLM 출력 중 "급여"와 "급여 유형"이 맞게 입력되었는지 재확인이 필요합니다.
            일급/주급/월급/연봉의 경우 그에 알맞는 일/주/월/년 근무시간으로 나누어 단위 시간당 급여로 환산해야합니다.[ 확인 요망 ]
            '''.format(hourly_wage, Min_hourly_wage, Max_hourly_wage)

            error_history = error_message(gpt_error, error_history)

    # ================================== 끝 ====================================
    return error_history, total_work_hours_per_week, hourly_wage

# @title 프롬프트
query_text_1 = """
당신은 긴 글을 읽고 중요한 정보들을 가독성 좋게 정리하는 일의 전문가처럼 답변할 것입니다.
맨 아래에 제시되는 약국 근무 약사 구인 공고에 관한 정보를 column별로 정리하여 데이터베이스에 추가하고자 합니다.
정리할 때는 다음의 규칙들을 준수해야 합니다.
규칙 1) 만약 공고글에 정보가 나와있지 않은 항목이 있다면, 가상으로 지어내지 말고 "명시되지 않음" 이라고 적어야 합니다.
규칙 2) 만약 공고글에 나타나 있는 근무유형이 2가지 이상이라면, 그 중 한가지 유형을 정하여 그 유형에 한해서만 작성합니다. 선택하지 않은 유형의 정보를 뒤섞어서 작성하면 안됩니다.
    아래 예시처럼 여러 근무유형 중 선택이 가능한 경우라면 그 중에 한가지 유형을 선택하여 일관성있게 작성하고, 선택하지 않은 유형에 대해서는 작성하지 않도록 해야합니다.
    (예시) 다음 중 선택 가능합니다 : 1) 주 2회 근무약사님 : 주중 평일 2일 근무(08:30~19:30) - 세후 월급 300만원. 2) 토요일 파트약사님 : 매주 토요일(08:30-14:00) 근무 - 시급 4만
규칙 3) wage, one_time_work_hourly_wage, hourly_wage를 작성할 때는 단위에 특히 주의해야 합니다. '만 원'(='10000원')을 단위로 사용하므로, 공고에 표시된 금액을 만원 단위로 환산해서 작성해야 합니다.
    (예시) 공고에 표시된 금액이 '30만원'인 경우 만원 단위로 환산시 30 입니다. (300 이 아닌 것에 주의하세요) 마찬가지로 '650만원' 의 경우 650 입니다. '55000원'의 경우 5.5 입니다. (제발 55와 같이 표기하지 마세요. 그건 thousand 단위입니다.)
규칙 4) 요일마다 또는 날짜마다 출퇴근 시각이 다르다면 평균값을 구해서 적습니다. 평균값을 계산하는 방법은 아래와 같습니다.
    (예시) 월,화 : 9시 출근 / 수,금 : 13시 출근 / 목 : 17시 출근 인 경우,
    평균값은 ((9*2)+(13*2)+(17*1))/5 = 12.2 입니다.
규칙 5) column에 해당하는 값을 적고, 왜 그렇게 적었는지 이유를 옆에 적도록 합니다.

Columns 설명) 데이터베이스는 다음과 같은 columns를 가지고 있습니다 :

# 1. 급여 정보
- is_salary_info : 공고에 급여 명시 여부. 해당 구인 공고에 급여가 구체적인 숫자로 나타나 있는지 여부입니다.
  연봉(annual), 월급(montly), 주급(weekly) 일당(daily), 시급(hourly wage) 중 하나라도 수치적으로 명시되어 있으면 True, '면접시 협의' 또는 공고글에 아예 명시되어 있지 않은 경우엔 False 입니다.
- is_after_tax : 표시된 급여가 세후(after-tax) 금액인지 여부. 세후(after-tax)라면 True, 세전(pre_tax)이라면 False. '세전계약', '세전금액' 등은 세전(pre-tax)임을 나타내는 단어입니다.
  '실수령'은 세후와 같은 의미이고, 공고글에 세전인지 세후인지를 추측할 수 있는 단어가 아무것도 없다면 그냥 세후로 간주하여 작성합니다.
- wage_type : 표시된 급여가 연봉(annual salary) 월급(montly wage), 주급(weekly wage), 일당(daily wage), 시급(hourly wage)인지 나타냅니다.
- wage : 표시된 급여 액수. 급여의 단위는 '만원' (='10000원')입니다. 예를 들어 1209600원인 경우 wage=120.96 입니다. 급여가 50만원 인경우, wage=50 입니다.
  만약 급여가 범위로서 표기되어 있는 경우, 범위 중 최소값을 선택하도록 합니다.

- one_time_work : 일회성으로 단기간(1일 ~ 2개월 이내)만 근무하는 조건인지 아닌지를 작성합니다. '3월27일 약사 구인', '휴가기간 동안 3일 근무해주실 분 구인' 등과 같이 특정 날짜를 지정하거나 특정 기간 동안만 근무할 것을 명시하는 경우에 일회성 근무가 됩니다.
  근무가 매주 반복되는 경우라면 지속성 근무에 해당합니다. 일회성 구인임을 명시하는 말이 없다면 그냥 지속성 근무로 간주합니다. 그리고 지속성 근무와 일회성 근무 둘 다 가능하다고 되어 있는 경우에는 지속성 근무라고 치고 작성하면 됩니다.

# 2. 일회성 근무일 경우. (if one_time_work == True:)
- one_time_work_days : 일회성 근무를 총 몇 일간 근무하는지 숫자로 나타냅니다. 예를 들어 5월 24, 25, 27일을 근무한다면 one_time_work_days = 3 입니다.
  만약 일회성 근무 기간이 6월17일 ~ 6월30일인데, 그중에서 실제적으로 근무하는 날짜가 총 6일이라면 one_time_work_days = 6 입니다.
- one_time_start_time : 일회성 근무 출근 시각이 몇 시인지 나타냅니다. 0~24시 형식으로 표기하고, 날짜마다 출근시각이 다르다면 평균값을 구해서 적습니다.
- one_time_end_time : 일회성 근무 퇴근 시각이 몇 시인지 나타냅니다. 0~24시 형식으로 표기하고, 날짜마다 퇴근시각이 다르다면 평균값을 구해서 적습니다.
- one_time_total_work_hours = (one_time_end_time - one_time_start_time) * one_time_work_days : 이 계산식으로 총 근무 시간을 계산하여 결과값을 숫자로 적습니다.
- one_time_work_hourly_wage : 일회성 근무의 시급을 '10,000원' 단위로 적습니다. 예를 들어 35,000원인 경우 one_time_work_hourly_wage = 3.5 입니다.
  만약 공고에 시급(hourly wage)으로 명시되어 있지 않고 일급(daily wage)이나 일하는 기간동안의 총 금액으로 적혀있는 경우에는 one_time_total_work_hours를 계산하여 '시급 = 급여/총근무시간'으로 환산하여 적도록 합니다.

# 3. 지속성 근무일 경우. (if one_time_work == False:)
- work_days : 월요일부터 일요일 중에 근무하는 요일을 콤마(,)로 구분하여 적습니다. (예시 : 월요일, 화요일, 수요일, 토요일)
[평일 근무 정보] : 월, 화, 수, 목, 금
- weekday_work_days : 평일(월요일~금요일) 중에 몇 일을 근무하는지 숫자로 나타냅니다. 예를 들어 화요일, 목요일, 토요일을 근무한다면 평일 근무 일수는 2일 입니다.
- weekday_start_time : 평일에 출근 시각이 몇 시인지 나타냅니다.0~24시 형식으로 표기하고, 요일마다 출근시각이 다르다면 평균값을 적습니다.
- weekday_end_time : 평일에 퇴근 시각이 몇 시인지 나타냅니다.0~24시 형식으로 표기하고, 요일마다 출근시각이 다르다면 평균값을 적습니다.
- weekday_total_work_hours = (weekday_end_time - weekday_start_time) * weekday_work_days : 이 계산식으로 평일 근무 시간을 계산하여 결과값을 숫자로 적습니다. (null 값으로 계산이 불가능한 경우에는 0시간으로 설정합니다.)
[주말 근무 정보] : 토요일, 일요일
- weekend_work_days : 주말(토요일, 일요일) 중에 몇일이나 근무하는지 숫자로 나타냅니다.(0~2 사이의 값) 격주(2주에 1번)로 근무하는 경우에는 0.5일로 치면 됩니다.
  예를들어, 매주 일요일 근무할 경우 weekend_work_days=1 이고, 격주 일요일 근무시 weekend_work_days=0.5 이며, 월1회(4주에 1번) 근무하면 weekend_work_days=0.25가 됩니다.
- weekend_start_time : 주말에 출근 시각이 몇 시인지 나타냅니다.0~24시 형식으로 표기하고, 요일마다 출근시각이 다르다면 평균값을 적습니다.
- weekend_end_time : 주말에 퇴근 시각이 몇 시인지 나타냅니다. 0~24시 형식으로 표기하고, 요일마다 출근시각이 다르다면 평균값을 적습니다.
- weekend_total_work_hours : (weekend_end_time - weekend_start_time) * weekend_work_days : 이 계산식으로 주말 근무 시간을 계산하여 결과값을 숫자로 적습니다. (null 값으로 계산이 불가능한 경우에는 0시간으로 설정합니다.)
[주당 총 근무시간, 월 총 근무시간 계산]
- total_work_hours_per_week : (weekday_work_days + weekend_work_days) : 이 계산식으로 주당 총 근무시간을 계산하여 결과값을 숫자로 적습니다.
- total_work_hours_per_month : (total_work_hours_per_week * 4.34) : 이 계산식으로 월 총 근무시간을 계산하여 결과값을 숫자로 적습니다.

# 4. 시급 계산식
- hourly_wage = wage / denominator 으로 시급을 계산하여 결과값을 숫자로 적습니다. 이때 denominator는 wage_type에 따라 아래와 같이 선택하면 됩니다.
만약 wage_type = 'annual'일 경우,
    denominator = total_work_hours_per_month * 12 로 연간 근무시간을 계산하여 설정합니다.
만약 wage_type = 'monthly'일 경우,
    denominator = total_work_hours_per_month 로 설정합니다.
만약 wage_type = 'weekly'일 경우,
    denominator = total_work_hours_per_week 로 설정합니다.
만약 wage_type = 'daily'일 경우,
    공고에서 주어진 정보를 바탕으로 work_hours_per_day (하루 근무 시간)을 계산하고,
    denominator = work_hours_per_day 로 설정합니다.
만약 wage_type = 'hourly'일 경우,
    denominator = 1 이 됩니다.
만약 wage_type이 명시되지 않았다면,
    기본 값으로 월 근무 시간을 사용합니다. 즉,
    denominator = total_work_hours_per_month 로 설정합니다.

# 5. 기타 정보
- monthly_leave : 월차를 제공하는지 여부입니다. 'O' 또는 'X'로 표기합니다.
- experience_requirement : 경력을 얼마나 요구하는지를 나타냅니다. '경력 무관', '경력 1년 이상', '경력 2년 이상', '경력 3년 이상' 중에 하나로 표기합니다.
- meal : 식사와 관련된 사항들. 밥은 약국 안에서 먹는지, 밖에서 자유롭게 먹고 오는지, 식비가 지원되는지 등등 식사와 관련된 사항들을 짧게 요약해서 작성합니다. 형식은 따로 없습니다.

아래의 글은 약국 근무 약사 구인 공고 글입니다 :
"""

query_text_2 = """
아래에 제시 되는 약국 근무 약사 구인 공고글의 내용을 다음과 같은 JSON 객체 형태로 작성해 주세요:

{
    "공고에 급여 명시 여부": (boolean),
    "세후 금액 여부": (boolean),
    "급여 유형" : (string | null),
    "급여": (number | null),
    "일회성 근무 여부": (boolean),
    "일회성 근무 일수": (number | null),
    "일회성 근무 출근 시각": (number | null),
    "일회성 근무 퇴근 시각": (number | null),
    "일회성 근무 총 근무 시간": (number | null),
    "일회성 근무 시급": (number | null),
    "근무 요일": (string | null),
    "평일 근무 일수": (number | null),
    "평일 출근 시각": (number | null),
    "평일 퇴근 시각": (number | null),
    "평일 총 근무 시간": (number | null),
    "주말 근무 일수": (number | null),
    "주말 출근 시각": (number | null),
    "주말 퇴근 시각": (number | null),
    "주말 총 근무 시간": (number | null),
    "주당 총 근무 시간": (number | null),
    "월 총 근무 시간": (number | null),
    "시급": (number | null),
    "월차": (string | null),
    "경력 요구": (string | null),
    "식사 관련": (string | null),
}

지켜야할 규칙은 다음과 같습니다.
규칙 1) 공고글에 정보가 나와있지 않은 항목이 있다면, 가상으로 지어내지 말고 null로 적어야 합니다.
규칙 2) "급여", "일회성 근무 시급", "시급"의 단위는 '만원'(='10000원')입니다. 예를 들어 1209600원인 경우 120.96으로 기록하세요. 마찬가지로 50만원 인경우, 50으로, 4만원인경우 4로 기록합니다.
규칙 3) 만약 공고글에 나타나 있는 근무유형이 2가지 이상이라면, 그 중 한가지 유형을 정하여 그 유형에 한해서만 작성합니다. 선택하지 않은 유형의 정보를 뒤섞어서 작성하면 안됩니다.
    아래 예시처럼 여러 근무유형 중 선택이 가능한 경우라면 그 중에 한가지 유형을 선택하여 일관성있게 작성하고, 선택하지 않은 유형에 대해서는 작성하지 않도록 해야합니다.
    (예시) 다음 중 선택 가능합니다 : 1) 주 2회 근무약사님 : 주중 평일 2일 근무(08:30~19:30) - 세후 월급 300만원. 2) 토요일 파트약사님 : 매주 토요일(08:30-14:00) 근무 - 시급 4만
규칙 4) 시각은 0~24시 형식으로 표기하고, 만약 요일마다 또는 날짜마다 출퇴근 시각이 다르다면 평균값을 구해서 적습니다. 평균값을 계산하는 방법은 아래와 같습니다.
    (예시) 월,화 : 9시 출근 / 수,금 : 13시 출근 / 목 : 17시 출근 인 경우,
    평균값은 ((9*2)+(13*2)+(17*1))/5 = 12.2 입니다.
규칙 5) 어떤 요일에 대해 격주(2주에 1번)로 근무하는 경우에는 근무 일수를 계산할 때 0.5일로 counting 하면 됩니다. 한달에 3주동안은 해당 요일에 근무하고 1주는 해당 요일에 휴무라면, 즉, 한달에 3/4만 근무한다면 0.75일로 counting 하면 됩니다.
    (예시1) 월~금 근무인데 금요일은 격주로(1,3주차만) 근무하는 경우에, "평일 근무 일수" : 4.5 (매주 월~목 : 4일 + 격주 금요일 : 0.5일)가 됩니다.
    (예시2) 매주 토요일 근무 & 일요일은 월1회 근무하는 경우에, "주말 근무 일수" : 1.25 (매주 토요일 : 1일 + 월1회(4주에 1번)일요일 : 0.25일)가 됩니다.
규칙 6) 만약 "일회성 근무 여부" : true 일 경우, 다음 항목들을 null로 설정하세요
    : "근무 요일", "평일 근무 일수", "평일 출근 시각", "평일 퇴근 시각", "평일 총 근무 시간", "주말 근무 일수", "주말 출근 시각", "주말 퇴근 시각", "주말 총 근무 시간", "주당 총 근무 시간", "월 총 근무 시간", "시급", "월차"
규칙 7) 만약 "일회성 근무 여부" : false 일 경우, 다음 항목들을 null로 설정하세요
    : "일회성 근무 일수", "일회성 근무 출근 시각", "일회성 근무 퇴근 시각", "일회성 근무 총 근무 시간", "일회성 근무 시급"
규칙 8) 시간 표시에 있어서 분 단위는 60으로 나누어서 시간 단위로 환산해서 표현하세요. 예를들어 8시30분은 8.5로, 17시50분은 17.833으로 표현합니다.
규칙 9) JSON형식에는 "A/(B*C)"와 같은 계산식이 들어갈 경우 오류가 발생합니다. 계산 과정이 있는 경우에는 계산을 모두 완료하여 최종 결과값만 숫자로 적도록 합니다. 아래의 예시를 참고하세요 :
    Negetive Example = {
        "월 총 근무 시간": 45 * 4.34,
        "시급": 650 / (45 * 4.34),
        "월차": "X"
    }
    Positive Example = {
        "월 총 근무 시간": 195.3,
        "시급": 3.327489,
        "월차": "X"
    }


아래의 글은 약국 근무 약사 구인 공고 글입니다 :
"""

"""# 3️⃣ main 코드"""

# @title main code

n = 0
# df의 각 row를 순차적으로 읽어서 변수에 할당하는 코드
for index, row in df.iterrows():
    # =============================== 변수 초기화 =================================
    # LLM이 만약 몇몇 변수를 빠뜨리고 할당을 안 할 경우, for문 돌면서 이전 공고의 정보가 다음 공고에 기록될수도 있어서
    error_history = ''
    llm_output_dict = None
    is_after_tax = None
    is_salary_info = None
    hourly_wage = None
    total_work_hours_per_week = None
    previous_llm_output = None
    refined_body = None
    final_answer = None
    salary = None
    net_salary = None
    # ==========================================================================

    # dataframe 정보 읽어오기
    print('='*25, n, '번 글', '='*25)
    # ========= 공고에 나와있는 오피셜한 정보들 =========
    posting_info_dict = row[['공고 제목', '등록일', '링크', '본문', '약국 명칭', '지역', '지역 대분류', '플랫폼']].to_dict()

    print('지역 대분류 :', row['지역 대분류'])
    print('지역 :', row['지역'])
    print('플랫폼 :', row['플랫폼'])
    print('링크 :', row['링크'])
    print('등록일 :', row['등록일'])
    print('약국 명칭 :', row['약국 명칭'])
    print(row['본문'])

    # ====== 에러 일으킨 이전 LLM model의 출력 =======
    row_prev = row[['LLM model', 'GPT Error', '공고에 급여 명시 여부', '세후 월급', '일회성 근무 여부', '일회성 근무 시급',
                   '평일 근무 일수', '평일 출근 시각', '평일 퇴근 시각', '주말 근무 일수', '주말 출근 시각', '주말 퇴근 시각',
                   '월차', '경력 요구', '식사 관련', 'GPT 2nd Run',
                   '시급(엄밀히)', '주당 근무 일수', '시간/month' # 노션에서 formula로 계산되어 나온 column들
                   ]]
    # ===========================================

    # string으로 변환해서 이전 LLM 출력을 notion DB에 참고용으로 업로드하기 위함
    # DataFrame을 dictionary로 변환한 후 JSON string으로 변환
    previous_llm_output = json.dumps(row_prev.to_dict(), ensure_ascii=False) # ensure_ascii=False (한글 깨짐 방지)

    # previous_llm_output의 길이를 최대 2000으로 제한 (노션 DB에 업로드할때 무슨 이유에선지 모르지만 2000을 넘어가면 업로드가 안됨)
    previous_llm_output = previous_llm_output[:2000]

    # print('$'* 50 ,'이전 LLM 출력')
    # print(previous_llm_output)

    # ========================= GPT-4o first run ================================
    # query_text_1 = """위에 cell로 따로 뺌"""
    query = query_text_1 + '\n글 본문 :\n' + row['본문']
    refined_body = run_llm(query, model_name=MODEL_NAME, run_name='First Run', few_shot=None)
    if refined_body is None:
        continue

    # ======================== GPT-4 second run ================================
    # query_text_2 = """위에 cell로 따로 뺌"""
    query_2 = query_text_2 + '\n' + refined_body
    final_answer = run_llm(query_2, model_name=MODEL_NAME, run_name='Second Run', few_shot=None)
    if final_answer is None:
        continue

    # GPT가 작성한 코드를 JSON 형태로 받아서 변수에 할당
    llm_output_dict, json_string = extract_json_from_response(final_answer)
    if llm_output_dict is None:
        continue
    print(llm_output_dict)
    # ==========================================================================

    # ======================== 급여 정보 없으면 패스 ================================
    is_after_tax = llm_output_dict['세후 금액 여부']

    is_salary_info = llm_output_dict['공고에 급여 명시 여부']
    if not is_salary_info:
        print('공고에 급여가 명시되지 않아서 {} 번째 공고는 pass 합니다. 다음 공고 찾는중...'.format(n))
        continue

    # ================= LLM 의 단위 실수로 시급이 10배로 나오는 case 보정 ===============
    if llm_output_dict['일회성 근무 여부']:
        if (llm_output_dict['일회성 근무 시급'] is not None) and (24 <= llm_output_dict['일회성 근무 시급'] <= 55):
            llm_output_dict['일회성 근무 시급'] /= 10
    else:
        # 시급이 24만원 ~ 55만원 범위로 나오는 경우, 단위 오류일 가능성 큼. (e.g. 시급=3으로 써야하는데 LLM이 30으로 써놓은 경우)
        if (llm_output_dict['시급'] is not None) and (24 <= llm_output_dict['시급'] <= 55):
            llm_output_dict['시급'] /= 10

        if (llm_output_dict['급여'] is not None) and (24 <= llm_output_dict['급여'] <= 55):
            if llm_output_dict['급여 유형'] in ['hourly', 'hourly wage', '시급']:
                llm_output_dict['급여'] /= 10


    # =========================== Error Check ==================================
    error_history, total_work_hours_per_week, hourly_wage = error_check(
        llm_output_dict,
        error_history=error_history,
        Min_hourly_wage=1.8,
        Max_hourly_wage=5.5
    )

    if llm_output_dict['일회성 근무 여부']:
        print('LLM output - 일회성 근무 시급 :', llm_output_dict['일회성 근무 시급'])
    else:
        print('표시된 급여 :', llm_output_dict['급여 유형'], llm_output_dict['급여'], f'( 세후 : {is_after_tax} )\n')

        print('ErrorCheck후 - 주당 근무 시간 :', total_work_hours_per_week, '시간')
        print('LLM output - 주당 근무 시간 :', llm_output_dict['주당 총 근무 시간'], '시간')
        print('ErrorCheck후 - 시급 :', hourly_wage, '만원')
        print('LLM output - 시급 :', llm_output_dict['시급'], '만원')
    print('에러 메시지 내역 :\n', error_history)
    # ==========================================================================

    if not llm_output_dict['일회성 근무 여부']:
        # ========================== 월 단위로 급여 환산 ================================
        # 월급 계산 : 노션에는 (지속성 근무일 경우) 일괄적으로 monthly wage로 통일해서 올리기로 했기 때문.
        if all([hourly_wage, total_work_hours_per_week]):
            # 근무일수 및 출퇴근시각 정보를 바탕으로 계산되는 hourly_wage 와 total_work_hours_per_week 가 None이 아니라면 우선적으로 사용.
            salary = hourly_wage * total_work_hours_per_week * 4.34
        else:
            # if all([llm_output_dict['주당 총 근무 시간'], llm_output_dict['시급']]):
            #     # LLM 이 계산한 시급과 총근무시간은 사칙연산이 틀리는 경우가 많지만 아쉬운대로 일단 사용...?
            #     salary = llm_output_dict['시급'] * llm_output_dict['주당 총 근무 시간'] * 4.34
            # else:
            #     salary = 0
            salary = 0
            gpt_error = '''
                    [ ERROR 발생 ] hourly_wage 와 total_work_hours_per_week 중 하나라도 None이 존재합니다.
                    일단 급여를 0으로 설정하였습니다. 재확인이 필요합니다. [ 확인 요망 ]
                    '''
            error_history = error_message(gpt_error, error_history)

        # ======================= 세전 -> 세후 월 급여 변환 ==============================
        if is_after_tax is False:  # 세전인 경우 (False일 때만)
            # 네이버 세후 월급 계산기로 세전(x) , 세후(y) 값들을 몇개 sampling해서 2차 함수로 regression 해봄.
            # 꽤 잘 맞는 식을 찾음. (오차가 조금 있긴한데, 대략적으로 맞으니까 괜찮을듯)
            # y = 5.35 + 0.904394x + -0.000143950695x^2
            net_salary = 5.35 + 0.904394 * salary + -0.000143950695 * salary**2
            print('세전 -> 세후로 환산된 월급 :', net_salary)
            salary = round(salary, 2)          # 소수점 둘째짜리까지 표시
            net_salary = round(net_salary, 2)  # 소수점 둘째짜리까지 표시
            final_answer = final_answer + '-'*10 + '\n세전 {} -> 세후로 전환한 급여값 : {}\n\n'.format(salary, net_salary)

        else:  # 세후 표시 또는 None인 경우 -> 세후로 간주
            net_salary = round(salary, 2)  # 소수점 둘째짜리까지 표시

        # =============== 에러 일으킨 이전 LLM model과 출력된 시급을 비교 ===================
        if total_work_hours_per_week:
            net_hourly_wage = net_salary / (total_work_hours_per_week * 365 / 7 / 12)
        else:
            net_hourly_wage = None

        LLM_COMPARE_THRESHOLD = 0.01
        if compare_values(net_hourly_wage, row['시급(엄밀히)'], threshold=LLM_COMPARE_THRESHOLD):
            print('\n[ 2가지 LLM이 각각 출력한 시급값이 일치합니다. ]')
            MODEL_NAME = MODEL_NAME + ' 그리고 ' + row['LLM model']
            final_answer = final_answer + '\n\n[ 2가지 LLM이 각각 출력한 시급값이 일치합니다.(차이 {}% 미만) ]'.format(LLM_COMPARE_THRESHOLD*100)
        else:
            gpt_error = '''
                    [ ERROR 발생 ] LLM간 의견 차이 {}% 이상 발생.
                    {} 가 출력한 시급값은 {} 만원인 반면,
                    이전 단계의 LLM({})은 시급을 {} 만원이라고 출력하였습니다.
                    어느 값이 맞는지 재확인이 필요합니다. [ 확인 요망 ]
                    '''.format(LLM_COMPARE_THRESHOLD*100, MODEL_NAME, net_hourly_wage, row['LLM model'], row['시급(엄밀히)'])
            error_history = error_message(gpt_error, error_history)
        # ==========================================================================
    else:
        LLM_COMPARE_THRESHOLD = 0.01
        if compare_values(llm_output_dict['일회성 근무 시급'], row['일회성 근무 시급'], threshold=LLM_COMPARE_THRESHOLD):
            print('\n[ 2가지 LLM이 각각 출력한 시급값이 일치합니다. ]')
            MODEL_NAME = MODEL_NAME + ' 그리고 ' + row['LLM model']
            final_answer = final_answer + '\n\n[ 2가지 LLM이 각각 출력한 시급값이 일치합니다.(차이 {}% 미만) ]'.format(LLM_COMPARE_THRESHOLD*100)
        else:
            gpt_error = '''
                    [ ERROR 발생 ] LLM간 의견 차이 {}% 이상 발생.
                    {} 가 출력한 시급값은 {} 만원인 반면,
                    이전 단계의 LLM({})은 시급을 {} 만원이라고 출력하였습니다.
                    어느 값이 맞는지 재확인이 필요합니다. [ 확인 요망 ]
                    '''.format(LLM_COMPARE_THRESHOLD*100, MODEL_NAME, llm_output_dict['일회성 근무 시급'], row['LLM model'], row['일회성 근무 시급'])
            error_history = error_message(gpt_error, error_history)


    task_setting_dict = {
        'New Data' : True,  # 노션상에서 새로 추가된 data인지 구분하기 위해 편의상 marker를 다는 것
        specific_date_new_data : True, # 노션상에서 특정 날짜에 새로 추가된 data인지 구분하기 위해 편의상 marker를 다는 것
        'Error 교정 작업' : True, # 노션상에서 에러 교정한 data인지 구분하기 위해 편의상 marker를 다는 것
        'Error났던 LLM 출력' : previous_llm_output, # 이전 LLM의 출력 참고용으로 기록해줌
        'LLM model' : MODEL_NAME, # 이번 Task에서 사용한 LLM model 이름
    }

    if error_history == '':
        error_history = None

    process_dict = { # LLM output을 바탕으로 이런저런 processing을 거친 결과  ->  dict_for_upload에 넣으면 됨
        'GPT 요약문' : refined_body,
        'GPT 2nd Run' : final_answer,
        'GPT Error' : error_history,
        '세후 월급' : net_salary,
    }

    dict_for_upload = {
        **task_setting_dict,
        **posting_info_dict,
        **llm_output_dict,
        **process_dict
    }

    # 위에서 MODEL_NAME 에 ' 그리고 '를 붙여서 변경된 경우, 다시 원래대로 복구
    MODEL_NAME = MODEL_NAME.split(' 그리고 ')[0]

    # ======================== 노션 DB 업로드 =====================================
    upload_notion_db(DATABASE_ID, NOTION_TOKEN, dict_for_upload)

    # 다음 번호 설정
    n += 1

"""quata를 다 써서 에러가 나는 경우, openAI 홈페이지에서 잔액을 충전했는데도 불구하고 계속 에러가 뜨면 런타임을 해제하고 다시 새로 연결해서 해보면 된다!"""

# @title 이전 LLM 출력을 GPT-4o한테 보여주려면 아래처럼 할당해서 넣어주면 될듯한데.. 일단은 안 보여주고 해봄
# is_salary_info = row['공고에 급여 명시 여부']
# one_time_work = row['단기근무']
# one_time_work_hourly_wage = row['단기근무 시급']
# error_history = row['GPT Error']
# gpt_output_history = row['GPT 2nd Run']
# net_salary = row['세후 급여']
# weekday_work_days = row['평일 근무 일수']
# weekday_start_time = row['평일 출근 시각']
# weekday_end_time = row['평일 퇴근 시각']
# weekend_work_days = row['주말 근무 일수']
# weekend_start_time = row['주말 출근 시각']
# weekend_end_time = row['주말 퇴근 시각']
# monthly_leave = row['월차']
# experience_requirement = row['경력 요구']
# meal = row['식사 관련']
# notion_hourly_wage = row['시급(엄밀히)']
# notion_work_days_per_week = row['주 근무일']
# notion_work_hours_per_month = row['시간/month']

"""# 임시) Gemini API

## ✦ Gemini API (유료) 🌟
: Gemini 1.5 flash - 싸고 성능 꽤 좋음

참고 : https://ai.google.dev/gemini-api/docs/get-started/tutorial?lang=python&hl=ko <br>
API 사용량, 비용 보는 곳 : https://console.cloud.google.com/billing/01BC5E-EC85E4-92339A?hl=ko&project=gen-lang-client-0011046539
"""

# !pip install -q -U google-generativeai

# Used to securely store your API key
import google.generativeai as genai
from google.colab import userdata

# Or use `os.getenv('GEMINI_API_KEY')` to fetch an environment variable.
GOOGLE_API_KEY = userdata.get("GOOGLE_API_KEY") # 좌측 🔑 열쇠모양 눌러서 보안 userdata로 api key를 저장하고 가져옴
genai.configure(api_key=GOOGLE_API_KEY)

# 사용 가능한 모델 목록 출력
for model in genai.list_models():
    print(model.name)

"""주어진 모델 목록에서 **가장 적합한 모델**은 사용 목적과 작업 유형에 따라 달라집니다. 아래는 주요 모델과 사용 용도에 대한 간략한 설명과 추천 사항입니다:

---

### **1. 대화형 AI 및 챗봇**
- **추천 모델**:  
  - `models/chat-bison-001`: 자연어 이해(NLU)와 대화 응답 생성에 적합합니다. 대화형 시스템이나 챗봇 제작에 사용하기 좋은 모델입니다.
  - **추천 이유**: 빠른 응답 시간과 안정성을 갖춘 모델로, 다양한 대화형 응용 프로그램에 활용 가능합니다.

---

### **2. 텍스트 생성 및 처리**
- **추천 모델**:  
  - `models/text-bison-001`: 창의적인 글쓰기, 텍스트 확장, 요약, 번역 등 다양한 텍스트 생성 작업에 최적화되어 있습니다.
  - **추천 이유**: 텍스트 중심 작업에 특화되어 있어 높은 성능을 기대할 수 있습니다.

---

### **3. 임베딩 생성 (유사도 검색, 의미 기반 검색 등)**
- **추천 모델**:  
  - `models/embedding-gecko-001`: 경량화된 임베딩 생성에 적합하며 빠르고 효율적인 결과를 제공합니다.  
  - `models/text-embedding-004`: 최신 임베딩 모델로, 더 높은 품질의 임베딩 생성과 의미 분석에 강점이 있습니다.
  - **추천 이유**: 유사도 계산이나 검색 시스템에서 성능이 우수하며, 특히 `text-embedding-004`는 가장 최신 기술을 반영합니다.

---

### **4. Gemini 계열 (종합적 고성능 모델)**
- **추천 모델**:  
  - `models/gemini-1.5-pro-latest`: 가장 최신의 안정화된 프로 모델로, 다목적 작업에 적합합니다.
  - `models/gemini-1.5-pro-vision-latest`: 비전(이미지)과 텍스트를 모두 처리하는 작업에 적합합니다.
  - **추천 이유**: Gemini 모델은 텍스트 생성, 대화형 AI, 다중 모드 입력(텍스트 + 비전) 등 고급 작업에 탁월한 성능을 제공합니다. 최신 모델은 최신 기술과 데이터로 학습되어 더 높은 품질의 결과를 기대할 수 있습니다.

---

### **5. 실험적 또는 최신 기술 테스트**
- **추천 모델**:  
  - `models/gemini-exp-1114`, `models/gemini-exp-1121`: 실험적 기능 테스트에 적합하며, 최신 기술을 적용한 결과를 얻을 수 있습니다.
  - **추천 이유**: 실험적으로 새로운 기능을 테스트하고 싶은 경우 적합합니다.

---
"""

MODEL_NAME = 'gemini-1.5-pro-latest' # @param ["gemini-1.5-flash-latest", "gemini-1.5-pro-latest", "gemini-exp-1121"]

model = genai.GenerativeModel(MODEL_NAME)
tokenizer = None  # api 쓰면 tokenizer 따로 필요없는데, 아래 코드에서 에러나지 않게 None으로 설정함

# response = model.generate_content("Explain AI to me like I'm a kid.")
# print(response.text)

# @title input처리 및 generation 하는 함수 정의
def run_llm(query, model_name=MODEL_NAME, run_name='Run', few_shot=None):
    prompt = """다음은 작업을 설명하는 instruction이며, 추가적인 맥락을 제공하는 입력과 함께 제공됩니다. 요청을 적절히 완료하는 response를 작성하세요.

    ### Instruction:
    {}

    ### Response:
    {}"""

    if few_shot is not None:
        query = query + '\n예시(few-shot) :\n' + few_shot + '\n'  # few_shot을 제공할 경우, query에 덧붙여 줌.
    else:
        pass

    try:
        inputs = prompt.format(
            query,
            "", # output - leave this blank for generation!
        )

        # Generation
        print('='*25, 'LLM ({}) {} '.format(model_name, run_name), '='*25)
        outputs = model.generate_content(inputs)
        refined_body = outputs.text

        print(refined_body)
        print('='*50, '\n\n')
        return refined_body
    except Exception as e:
        print('\n' + '🆘'*50 + '\n', n, '번 글 at {}\n'.format(run_name), e, '\n' + '🆘'*50 + '\n')
        return None

# @title LLM response로부터 JSON 뽑는 함수
def extract_json_from_response(response):
    '''
    LLM의 응답을 JSON 형식으로 파싱하여 dict를 반환하는 함수
    '''
    # regex를 사용하여 dictionary 부분만 추출
    pattern = re.compile(r'\{.*\}', re.DOTALL)
    match = pattern.search(response)

    if match:
        json_string = match.group()

        try:
            # 정규 표현식을 사용하여 모든 주석 제거 (// 스타일 주석과 /* */ 스타일 주석)
            json_string = re.sub(r'//.*?(?=\n)|/\*.*?\*/', '', json_string, flags=re.S)

            # 문자열을 Python dictionary로 변환
            result_dict = json.loads(json_string)
            return result_dict, json_string

        except json.JSONDecodeError as e:
            print("JSON is invalid")
            print('JSON string :\n', json_string)
            print(f"Error: {e}")
            return None, json_string
    else:
        print("LLM output에서 dictionary pattern을 추출할 수 없습니다.")
        return None, None

# @title gemini api 테스트 코드 (rate limit 걸리면 계속 무한정 뺑뺑이 돌면서 실행 안될 때가 있음;;)
import time
inputs = {
    "parts": [
        {"text": "Say hello if you are available. This is for test."}  # 'text' 키를 사용해 입력 내용을 전달
    ]
}
start_time = time.time()
try:
    outputs = model.generate_content(inputs).text
    print("Response:\n", outputs)
except Exception as e:
    print(f"Error: {e}")
finally:
    elapsed_time = time.time() - start_time
    print(f"Elapsed time: {elapsed_time:.2f} seconds")

"""quata를 다 써서 에러가 나는 경우, 구글 콘솔에서 결제 수단에 이상이 없는 데도 불구하고 계속 무한 뺑뺑이 돌면 런타임을 해제하고 다시 새로 연결해서 해보면 된다!"""